'use strict';

require('./init.moment');

module.exports = {
    'Button': require('./components/Button.js'),
    'ButtonLoading': require('./components/ButtonLoading.js'),
    'CalendarMonth': require('./components/CalendarMonth.js'),
    'ChartLegend': require('./components/ChartLegend.js'),
    'CheckBox': require('./components/CheckBox.js'),
    'CheckBoxList': require('./components/CheckBoxList.js'),
    'ColorPicker': require('./components/ColorPicker.js'),
    'ColorPickerNew': require('./components/ColorPickerNew.js'),
    'ContextMenu': require('./components/ContextMenu.js'),
    'DatePicker': require('./components/DatePicker.js'),
    'DateRangePicker': require('./components/DateRangePicker.js'),
    'DropDownContent': require('./components/DropDownContent.js'),
    'EditableList': require('./components/EditableList.js'),
    'ErrorMessage': require('./components/ErrorMessage.js'),
    'ExportButton': require('./components/ExportButton.js'),
    'FieldRow': require('./components/FieldRow.js'),
    'Fieldset': require('./components/Fieldset.js'),
    'FileUploader': require('./components/FileUploader.js'),
    'FillPicker': require('./components/FillPicker.js'),
    'FilterableContent': require('./components/FilterableContent.js'),
    'GeoChart': require('./components/GeoChart.js'),
    'GradientPicker': require('./components/GradientPicker.js'),
    'Header': require('./components/Header.js'),
    'Icon': require('./components/Icon.js'),
    'ImageUploader': require('./components/ImageUploader.js'),
    'InlineTooltip': require('./components/InlineTooltip.js'),
    'Input': require('./components/Input.js'),
    'LineChart': require('./components/LineChart.js'),
    'Loading': require('./components/Loading.js'),
    'Map': require('./components/Map.js'),
    'Modal': require('./components/Modal.js'),
    'MultiSelect': require('./components/MultiSelect.js'),
    'OptionSwitch': require('./components/OptionSwitch.js'),
    'PieChart': require('./components/PieChart.js'),
    'PromiseLoader': require('./components/PromiseLoader.js'),
    'RadioList': require('./components/RadioList.js'),
    'Range': require('./components/Range.js'),
    'ScrollableContent': require('./components/ScrollableContent.js'),
    'Select': require('./components/Select.js'),
    'Sidebar': require('./components/Sidebar.js'),
    'Sticky': require('./components/Sticky.js'),
    'Table': require('./components/Table.js'),
    'Tabs': require('./components/Tabs.js'),
    'Text': require('./components/Text.js'),
    'Tooltip': require('./components/Tooltip.js'),
    'ViewportLoader': require('./components/ViewportLoader.js'),
    'Well': require('./components/Well.js')
};
